include:
  - project: 'deploy-app/fe-scripts'
    ref: master
    file: '/jobs/shared-jobs/run-linked-branch-pipelines.gitlab-ci.yml'

default:
  image: node:lts-slim

stages:
  - test

lint:scss:
  stage: test
  interruptible: true
  only:
    - master
    - merge_requests
  script:
    - npm ci
    - npm run lint:scss

lint:svg:
  stage: test
  only:
    - master
    - merge_requests
  tags:
    - medium
  interruptible: true
  variables:
    NODE_OPTIONS: '--max_old_space_size=4000'
  script:
    - ./tasks/lint-svg.sh


run-app-pipeline:
  extends: .run-linked-branch-pipelines-shared
  stage: test
